import { createHash } from 'node:crypto';
import { mkdir,readFile,writeFile,cp,rm,chmod } from 'node:fs/promises';
import { createWriteStream } from 'node:fs';
import { Readable } from 'node:stream';
import { pipeline } from 'node:stream/promises';
import { spawnSync } from 'node:child_process';
import { dirname,join,resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const root=dirname(dirname(fileURLToPath(import.meta.url)));
const version='24.19.0';
const platform=process.env.NAVER_MAIL_PACKAGE_PLATFORM??process.platform;
const arch=process.env.NAVER_MAIL_PACKAGE_ARCH??process.arch;
if(!['win32-x64','darwin-x64','darwin-arm64'].includes(`${platform}-${arch}`))throw new Error('Unsupported release target');
const os=platform==='win32'?'win':'darwin';
const archive=`node-v${version}-${os}-${arch}.${platform==='win32'?'zip':'tar.gz'}`;
const base=`https://nodejs.org/dist/v${version}/`;
const target=join(root,'runtime',`${platform}-${arch}`);
const temp=join(root,'.build-runtime',`${platform}-${arch}`);await mkdir(temp,{recursive:true});
const sumResponse=await fetch(base+'SHASUMS256.txt');if(!sumResponse.ok)throw new Error('Unable to fetch Node release checksums');
const sums=await sumResponse.text();const expected=sums.split('\n').find(line=>line.trim().endsWith(' '+archive))?.trim().split(/\s+/)[0];
if(!expected)throw new Error('Pinned Node runtime not found in release checksums');
const response=await fetch(base+archive);if(!response.ok||!response.body)throw new Error('Unable to download Node runtime');
const file=join(temp,archive);await pipeline(Readable.fromWeb(response.body),createWriteStream(file));
const actual=createHash('sha256').update(await readFile(file)).digest('hex');if(actual!==expected)throw new Error('Node runtime checksum mismatch');
const extracted=join(temp,'extracted');await mkdir(extracted,{recursive:true});
// Node's official archives are extracted by the OS archive tool, without install scripts.
const folder=`node-v${version}-${os}-${arch}`;
const node=platform==='win32'?'node.exe':'bin/node';
const result=spawnSync('tar',['-xf',file,'-C',extracted,`${folder}/${node}`,`${folder}/LICENSE`],{stdio:'inherit',windowsHide:true});if(result.status!==0)throw new Error('Runtime extraction failed');
const release=join(extracted,folder);await mkdir(target,{recursive:true});
await mkdir(dirname(join(target,node)),{recursive:true});
await cp(join(release,node),join(target,node));if(platform!=='win32')await chmod(join(target,node),0o755);
await cp(join(release,'LICENSE'),join(target,'LICENSE'));
await writeFile(join(target,'runtime.json'),JSON.stringify({version,platform,arch,source:base+archive,sha256:expected},null,2)+'\n');
if(!resolve(temp).startsWith(resolve(root,'.build-runtime')+ (process.platform==='win32'?'\\':'/')))throw new Error('Unsafe cleanup path');
await rm(temp,{recursive:true,force:true});
console.log(`Bundled Node ${version}: ${platform}-${arch}`);
