export function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/gu, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
}

export function renderForm(path: string, error = "", expiresAt = Date.now() + 1_800_000): string {
  const base=escapeHtml(path);
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>네이버 메일 연결 · Eziwork</title><link rel="stylesheet" href="${base}/assets/setup.css"><script src="${base}/assets/setup.js" defer></script></head><body>
<main data-base="${base}" data-expires="${expiresAt}">
<header><span class="brand">EZIWORK <span>비공식 네이버 메일 연결</span></span><h1>메일 연결, 차근차근 함께해요</h1><p class="lead">한 번 연결하면 앱에서 메일을 찾고 답장을 준비할 수 있어요.</p></header>
<ol class="progress" aria-label="연결 순서"><li aria-current="step">1 <span>보안 설정</span></li><li>2 <span>메일 허용</span></li><li>3 <span>비밀번호 입력</span></li><li>4 <span>연결 확인</span></li></ol>
<div id="notice" class="notice" role="alert" ${error?'':'hidden'}>${escapeHtml(error)}</div>
<section data-step="1" aria-labelledby="step-1-title"><span class="eyebrow">처음 연결할 때 한 번만</span><h2 id="step-1-title" tabindex="-1">네이버에서 2단계 인증을 켜 주세요</h2><p>네이버 로그인 후 <b>보안설정 → 2단계 인증</b>으로 이동해요. 이미 <b>관리</b> 버튼이 보이면 준비된 상태예요.</p><a class="button primary" href="https://nid.naver.com/user2/help/myInfoV2?m=viewSecurity&amp;lang=ko_KR" target="_blank" rel="noopener noreferrer">네이버 보안설정 열기 ↗</a><figure><img src="${base}/assets/two-factor-security.png" alt="네이버 보안설정의 2단계 인증 설정 또는 관리 버튼"><figcaption>네이버 화면에서 진행한 뒤 이 창으로 돌아오세요.</figcaption></figure><p class="hint">일반 로그인 비밀번호는 네이버 사이트에서만 입력해요.</p><footer><button class="text" type="button" data-go="3">이미 준비했어요 · 바로 입력</button><button class="primary" type="button" data-go="2">준비했어요, 다음</button></footer></section>
<section data-step="2" aria-labelledby="step-2-title" hidden><span class="eyebrow">메일 앱이 연결될 수 있도록</span><h2 id="step-2-title" tabindex="-1">IMAP/SMTP를 ‘사용함’으로 저장해요</h2><p>네이버 메일 <b>환경설정 → POP3/IMAP 설정 → IMAP/SMTP 설정</b>에서 ‘사용함’을 선택하고 <b>저장</b>해 주세요.</p><a class="button primary" href="https://mail.naver.com/v2/settings/smtp/imap" target="_blank" rel="noopener noreferrer">네이버 메일 설정 열기 ↗</a><figure><img src="${base}/assets/imap-smtp-enable.png" alt="IMAP SMTP 사용함 선택과 저장 위치"><figcaption>IMAP은 메일 조회, SMTP는 발송을 위한 연결 설정이에요.</figcaption></figure><details><summary>다른 화면이 보이거나 오래된 메일이 안 보이나요?</summary><p>POP3 탭이 보이면 오른쪽 <b>IMAP/SMTP 설정</b> 탭으로 이동해 주세요. 이 플러그인은 POP3를 사용하지 않습니다. 과거 메일 조회 범위는 <b>IMAP 동기화 메일 제한</b>과 네이버에 보관된 메일에 따라 달라져요.</p><a href="https://help.naver.com/service/30029/contents/21344?osType=COMMONOS" target="_blank" rel="noopener noreferrer">네이버 공식 도움말 ↗</a></details><footer><button type="button" data-go="1">이전</button><button class="primary" type="button" data-go="3">저장했어요, 다음</button></footer></section>
<section data-step="3" aria-labelledby="step-3-title" hidden><span class="eyebrow">마지막 준비</span><h2 id="step-3-title" tabindex="-1">앱 전용 비밀번호를 붙여 넣어 주세요</h2><p>네이버 <b>2단계 인증 → 관리 → 애플리케이션 비밀번호 관리</b>에서 직접 입력을 선택하고 <b>Codex Naver Mail</b>이라는 이름으로 생성해요.</p><details><summary>비밀번호 만드는 화면 보기</summary><figure><img src="${base}/assets/application-password.png" alt="애플리케이션 비밀번호 직접 입력, 생성하기, 비밀번호 확인 순서"><figcaption>생성된 비밀번호를 아래 입력란에 붙여 넣으세요. 대화창에는 입력하지 마세요.</figcaption></figure><a href="https://help.naver.com/service/5640/contents/8584?lang=ko" target="_blank" rel="noopener noreferrer">네이버 공식 비밀번호 안내 ↗</a></details>
<form id="connect-form" method="post" action="${base}/api/connect" autocomplete="off"><label for="email">네이버 메일 주소</label><div class="email-field"><input id="email" name="email" type="text" inputmode="email" autocomplete="username" placeholder="네이버 아이디 또는 이메일" required maxlength="254"></div><label for="appPassword">애플리케이션 비밀번호</label><div class="password-field"><input id="appPassword" name="appPassword" type="password" autocomplete="off" required minlength="4" maxlength="256"><button id="toggle-password" type="button" aria-controls="appPassword" aria-pressed="false">보기</button></div><p class="hint">일반 네이버 로그인 비밀번호가 아닌 새로 생성한 앱 비밀번호예요.</p><label class="check"><input name="acknowledge" type="checkbox" value="yes" required><span>네이버에서 만든 앱 비밀번호를 입력했어요.</span></label><footer><button type="button" data-go="2">이전</button><button class="primary" id="connect-button" type="submit">연결 확인하기</button></footer></form></section>
<section data-step="4" aria-labelledby="step-4-title" hidden><span class="eyebrow">연결 확인</span><h2 id="step-4-title" tabindex="-1">연결을 확인하고 있어요</h2><p id="connection-message" aria-live="polite">잠시만 기다려 주세요. 테스트 메일을 발송하지 않습니다.</p><ol class="checks"><li data-check="imap">메일 조회 연결 확인</li><li data-check="smtp">메일 발송 연결 확인</li><li data-check="storage">컴퓨터 보안 저장소에 저장</li></ol><div id="success" hidden><div class="success-icon" aria-hidden="true">✓</div><p>앱으로 돌아가 이렇게 요청해 보세요.</p><blockquote>“최근 받은 중요한 메일을 정리해 줘.”</blockquote><button type="button" id="finish-button" class="primary">완료</button><p class="hint">이 창을 닫아도 연결 정보는 안전하게 보관돼요.</p></div><button type="button" id="retry-button" data-go="3" hidden>입력 화면으로 돌아가기</button></section>
<aside class="privacy"><b>입력한 비밀번호는 이 컴퓨터의 보안 저장소에 보관돼요.</b><p>조회·발송은 컴퓨터에서 네이버 서버로 직접 연결합니다. 선택한 메일 내용은 Codex·Work의 모델 처리에 사용될 수 있어요. 이 플러그인은 Eziwork의 비공식 도구입니다.</p><span id="expiry-note">연결 화면은 30분 동안 사용할 수 있어요.</span></aside><noscript><p class="notice">연결 화면을 사용하려면 이 로컬 페이지의 JavaScript를 허용해 주세요.</p></noscript>
</main></body></html>`;
}
